var commanderSettings = [
    controllerIP = '',
    companionIP = '',
    companionPort = '',
    button1 = '',
    button2 = '',
    button3 = '',
    button4 = '',
    button5 = '',
    button6 = '',
    button7 = '',
    button8 = '',
    button9 = '',
    button10 = '',
    button11 = '',
    button12 = '',
    button13 = '',
    button14 = '',
    button15 = '',
    button16 = '',
    button17 = '',
    button18 = '',
    button19 = '',
    button20 = '',
    button21 = '',
    button22 = '',
    button23 = '',
    button24 = '',
    button25 = '',
    button26 = '',
    button27 = '',
    button28 = '',
    button29 = '',
    button30 = '',
    button31 = '',
    button32 = '',
    button33 = '',
    button34 = '',
    button35 = '',
    button36 = '',
    button37 = '',
    button38 = '',
    button39 = '',
    button40 = ''
]

function setupCommanderSettings() {
    commanderSettings = [
        controllerIP = this.config.controllerIP,
        companionIP = this.config.companionIP,
        companionPort = this.config.companionPort,
        button1 = this.config.button1,
        button2 = this.config.button2,
        button3 = this.config.button3,
        button4 = this.config.button4,
        button5 = this.config.button5,
        button6 = this.config.button6,
        button7 = this.config.button7,
        button8 = this.config.button8,
        button9 = this.config.button9,
        button10 = this.config.button10,
        button11 = this.config.button11,
        button12 = this.config.button12,
        button13 = this.config.button13,
        button14 = this.config.button14,
        button15 = this.config.button15,
        button16 = this.config.button16,
        button17 = this.config.button17,
        button18 = this.config.button18,
        button19 = this.config.button19,
        button20 = this.config.button20,
        button21 = this.config.button21,
        button22 = this.config.button22,
        button23 = this.config.button23,
        button24 = this.config.button24,
        button25 = this.config.button25,
        button26 = this.config.button26,
        button27 = this.config.button27,
        button28 = this.config.button28,
        button29 = this.config.button29,
        button30 = this.config.button30,
        button31 = this.config.button31,
        button32 = this.config.button32,
        button33 = this.config.button33,
        button34 = this.config.button34,
        button35 = this.config.button35,
        button36 = this.config.button36,
        button37 = this.config.button37,
        button38 = this.config.button38,
        button39 = this.config.button39,
        button40 = this.config.button40
    ]
}

module.exports = {
    commanderSettings,
    setupCommanderSettings
};