 var bankchoices = [
        {id: '100', label: 'None'},
        {id: '1', label: 'Bank 1'},
        {id: '2', label: 'Bank 2'},
        {id: '3', label: 'Bank 3'},
        {id: '4', label: 'Bank 4'},
        {id: '5', label: 'Bank 5'},
        {id: '6', label: 'Bank 6'},
        {id: '7', label: 'Bank 7'},
        {id: '8', label: 'Bank 8'},
        {id: '9', label: 'Bank 9'},
        {id: '10', label: 'Bank 10'},
        {id: '11', label: 'Bank 11'},
        {id: '12', label: 'Bank 12'},
        {id: '13', label: 'Bank 13'},
        {id: '14', label: 'Bank 14'},
        {id: '15', label: 'Bank 15'},
        {id: '16', label: 'Bank 16'},
        {id: '17', label: 'Bank 17'},
        {id: '18', label: 'Bank 18'},
        {id: '19', label: 'Bank 19'},
        {id: '20', label: 'Bank 20'},
        {id: '21', label: 'Bank 21'},
        {id: '22', label: 'Bank 22'},
        {id: '23', label: 'Bank 23'},
        {id: '24', label: 'Bank 24'},
        {id: '25', label: 'Bank 25'},
        {id: '26', label: 'Bank 26'},
        {id: '27', label: 'Bank 27'},
        {id: '28', label: 'Bank 28'},
        {id: '29', label: 'Bank 29'},
        {id: '30', label: 'Bank 30'},
        {id: '31', label: 'Bank 31'},
        {id: '32', label: 'Bank 32'},
        {id: '33', label: 'Bank 33'},
        {id: '34', label: 'Bank 34'},
        {id: '35', label: 'Bank 35'},
        {id: '36', label: 'Bank 36'},
        {id: '37', label: 'Bank 37'},
        {id: '38', label: 'Bank 38'},
        {id: '39', label: 'Bank 39'},
        {id: '40', label: 'Bank 40'},
        {id: '41', label: 'Bank 41'},
        {id: '42', label: 'Bank 42'},
        {id: '43', label: 'Bank 43'},
        {id: '44', label: 'Bank 44'},
        {id: '45', label: 'Bank 45'},
        {id: '46', label: 'Bank 46'},
        {id: '47', label: 'Bank 47'},
        {id: '48', label: 'Bank 48'},
        {id: '49', label: 'Bank 49'},
        {id: '50', label: 'Bank 50'},
        {id: '51', label: 'Bank 51'},
        {id: '52', label: 'Bank 52'},
        {id: '53', label: 'Bank 53'},
        {id: '54', label: 'Bank 54'},
        {id: '55', label: 'Bank 55'},
        {id: '56', label: 'Bank 56'},
        {id: '57', label: 'Bank 57'},
        {id: '58', label: 'Bank 58'},
        {id: '59', label: 'Bank 59'},
        {id: '60', label: 'Bank 60'},
        {id: '61', label: 'Bank 61'},
        {id: '62', label: 'Bank 62'},
        {id: '63', label: 'Bank 63'},
        {id: '64', label: 'Bank 64'},
        {id: '65', label: 'Bank 65'},
        {id: '66', label: 'Bank 66'},
        {id: '67', label: 'Bank 67'},
        {id: '68', label: 'Bank 68'},
        {id: '69', label: 'Bank 69'},
        {id: '70', label: 'Bank 70'},
        {id: '71', label: 'Bank 71'},
        {id: '72', label: 'Bank 72'},
        {id: '73', label: 'Bank 73'},
        {id: '74', label: 'Bank 74'},
        {id: '75', label: 'Bank 75'},
        {id: '76', label: 'Bank 76'},
        {id: '77', label: 'Bank 77'},
        {id: '78', label: 'Bank 78'},
        {id: '79', label: 'Bank 79'},
        {id: '80', label: 'Bank 80'},
        {id: '81', label: 'Bank 81'},
        {id: '82', label: 'Bank 82'},
        {id: '83', label: 'Bank 83'},
        {id: '84', label: 'Bank 84'},
        {id: '85', label: 'Bank 85'},
        {id: '86', label: 'Bank 86'},
        {id: '87', label: 'Bank 87'},
        {id: '88', label: 'Bank 88'},
        {id: '89', label: 'Bank 89'},
        {id: '90', label: 'Bank 90'},
        {id: '91', label: 'Bank 91'},
        {id: '92', label: 'Bank 92'},
        {id: '93', label: 'Bank 93'},
        {id: '94', label: 'Bank 94'},
        {id: '95', label: 'Bank 95'},
        {id: '96', label: 'Bank 96'},
        {id: '97', label: 'Bank 97'},
        {id: '98', label: 'Bank 98'},
        {id: '99', label: 'Bank 99'}
    ];

var buttonChoices = [
        {id: '100', label: 'None'},
        {id: '1', label: 'Button 1'},
        {id: '2', label: 'Button 2'},
        {id: '3', label: 'Button 3'},
        {id: '4', label: 'Button 4'},
        {id: '5', label: 'Button 5'},
        {id: '6', label: 'Button 6'},
        {id: '7', label: 'Button 7'},
        {id: '8', label: 'Button 8'},
        {id: '9', label: 'Button 9'},
        {id: '10', label: 'Button 10'},
        {id: '11', label: 'Button 11'},
        {id: '12', label: 'Button 12'},
        {id: '13', label: 'Button 13'},
        {id: '14', label: 'Button 14'},
        {id: '15', label: 'Button 15'},
        {id: '16', label: 'Button 16'},
        {id: '17', label: 'Button 17'},
        {id: '18', label: 'Button 18'},
        {id: '19', label: 'Button 19'},
        {id: '20', label: 'Button 20'},
        {id: '21', label: 'Button 21'},
        {id: '22', label: 'Button 22'},
        {id: '23', label: 'Button 23'},
        {id: '24', label: 'Button 24'},
        {id: '25', label: 'Button 25'},
        {id: '26', label: 'Button 26'},
        {id: '27', label: 'Button 27'},
        {id: '28', label: 'Button 28'},
        {id: '29', label: 'Button 29'},
        {id: '30', label: 'Button 30'},
        {id: '31', label: 'Button 31'},
        {id: '32', label: 'Button 32'},
    ];



module.exports = {
    bankchoices,
    buttonChoices
};